#!/usr/bin/env bash
# Re-burn captions onto the v4 WHY-videos and write the v5 captioned track.
# Idempotent: re-running produces identical output. Reads .srt timings from
# campaign/assets/why-{1-pain,2-gate,3-proof}.srt and PNG strips from
# /tmp/captions/why-N-{pain,gate,proof}-cap-{1,2}.png (generated by
# render_captions.py). Writes captioned MP4s back to campaign/assets/.
#
# Usage:
#   bash campaign/scripts/burn_captions.sh
#
# Requires: ffmpeg with H.264 + AAC (this repo's release.yml uses the same
# pinned action), Pillow (`pip install Pillow`).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ASSETS="${REPO_ROOT}/campaign/assets"
TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

echo "→ regenerating caption PNG strips (Pillow / Verdana Bold 64px)"
python3 "${ASSETS}/render_captions.py" --out "${TMP}" >/dev/null

declare -A SPECS=(
  ["why-1-explainer"]="${ASSETS}/why-1-explainer.mp4:${ASSETS}/why-1-pain.srt"
  ["why-2-explainer"]="${ASSETS}/why-2-explainer.mp4:${ASSETS}/why-2-gate.srt"
  ["why-3-explainer"]="${ASSETS}/why-3-explainer.mp4:${ASSETS}/why-3-proof.srt"
)

for stem in "${!SPECS[@]}"; do
  IFS=':' read -r mp4 srt <<<"${SPECS[$stem]}"
  # Pull chunk timings from the .srt (line: "00:00:01,200 --> 00:00:03,800")
  IFS=' ' read -r T1_START T1_END <<<"$(awk 'NR==2' "${srt}" | awk -F'[ ,]' '{print $1, $3}')"
  IFS=' ' read -r T2_START T2_END <<<"$(awk 'NR==5' "${srt}" | awk -F'[ ,]' '{print $1, $3}')"
  # Convert HH:MM:SS,mmm → seconds with decimals
  ts() { awk -F'[:,]' '{printf "%.3f", $1*3600 + $2*60 + $3 + $4/1000}' <<<"$1"; }
  T1S="$(ts "${T1_START}")"; T1E="$(ts "${T1_END}")"
  T2S="$(ts "${T2_START}")"; T2E="$(ts "${T2_END}")"

  out="${ASSETS}/${stem}-captioned.mp4"
  cap1="${TMP}/${stem/-explainer/-pain}-cap-1.png"
  cap2="${TMP}/${stem/-explainer/-pain}-cap-2.png"
  echo "→ ${stem}: cap1 ${T1S}-${T1E}s, cap2 ${T2S}-${T2E}s → ${out}"

  ffmpeg -y -hide_banner -loglevel error \
    -i "${mp4}" -i "${cap1}" -i "${cap2}" \
    -filter_complex "[1:v]format=rgba[c1]; [2:v]format=rgba[c2]; \
      [0:v][c1]overlay=enable='between(t,${T1S},${T1E})':x=(W-w)/2:y=H-h-60[v1]; \
      [v1][c2]overlay=enable='between(t,${T2S},${T2E})':x=(W-w)/2:y=H-h-60[v]" \
    -map "[v]" -map 0:a? \
    -c:v libx264 -pix_fmt yuv420p -preset medium -crf 22 \
    -c:a copy \
    "${out}"
done

echo "✓ captioned track written:"
ls -lh "${ASSETS}"/*-captioned.mp4
